---
title: "Intro to R - Coding"
author: "Holly Martin & Jimmy Breen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



Loading our libraries (the software we'll be using)
```{r}
library(tidyverse)
```

# Loading data into RStudio

Wildlife of Newfoundland datasets

```{r, message=FALSE}
# Data on the number of Caribou and Moose in Newfoundland by year.
population <- read_csv("data/population.csv") 

# Data on the number of Coyote, Wolf and Lynx pelts sold in Newfoundland each year.
pelts <- read_csv("data/pelts.csv")
```

## Let's have a look at our data

```{r}
tibble(population)
```

```{r}
tibble(pelts)
```


```{r}
pelts %>% sample_n(nrow(.))
```

## Make our first plot

First let's make the plot layout.

```{r}
# Take the population data and plot the population of Moose and Caribou by Year.
population %>% # Data input
  ggplot(aes(x = Year, y = Population)) #  How the axes should be plotted
```

Add our data to the plot with a line coloured by species.

```{r}
# Take the population data and plot the population of Moose and Caribou by Year.
population %>% # Data input
  ggplot(aes(x = Year, y = Population)) + # How the axes should be plotted
  geom_line(aes(color=Species)) # Use a line for plotting and color the line by species
```

Add a Title and Subtitle to give some context to the plot.

```{r}
# Take the population data and plot the population of Moose and Caribou by Year.
population %>% # Data input
  ggplot(aes(x = Year, y = Population)) + # How the data should be plotted
  geom_line(aes(color=Species)) + # Use a line for plotting and color the line by species
labs(title = "Population of Wildlife in Newfoundland",
     subtitle = "1980-2007") # Add a Title and Subtitle to the plot
```

Make it look a little nicer.

```{r}
# Take the population data and plot the population of Moose and Caribou by Year.
population %>% # Data input
  ggplot(aes(x = Year, y = Population)) + # How the data should be plotted
  geom_line(aes(color=Species)) + # Use a line for plotting and color the line by species
labs(title = "Population of Wildlife in Newfoundland",
     subtitle = "1980-2007") + # Add a Title and Subtitle to the plot
  theme_bw(base_rect_size = 0.25) # Make it prettier
```


## Pelts sold


```{r}
pelts %>% # Use the pelts dataset for plotting
  ggplot(aes(x = Year, y = Pelts)) + # Year on x axis, Pelts on y axis
  geom_point(aes(color=Species)) + # Plot a point for each datapoint
  geom_line(aes(color=Species)) + # Plot a line to connect datapoints
  labs(title = "Pelts sold in Newfoundland, Canada",
       subtitle = "1993-2013") + # Add a title and subtitle
  theme_bw(base_rect_size = 0.25) # Use nicer theme
```



```{r}
pelts %>% # Use the pelts dataset for plotting
  ggplot(aes(x = Year, y = Pelts)) + # Year on x axis, Pelts on y axis
  geom_point(aes(color=Species)) + # Plot a point for each datapoint
  geom_line(aes(color=Species)) + # Plot a line to connect datapoints
  labs(title = "Pelts sold in Newfoundland, Canada",
       subtitle = "1993-2013") + # Add a title and subtitle
  theme_minimal(base_rect_size = 0.25) # Use nicer theme
```

```{r}
pelts %>% # Use the pelts dataset for plotting
  ggplot(aes(x = Year, y = Pelts)) + # Year on x axis, Pelts on y axis
  geom_point(aes(color=Species)) + # Plot a point for each datapoint
  geom_line(aes(color=Species)) + # Plot a line to connect datapoints
  labs(title = "Pelts sold in Newfoundland, Canada",
       subtitle = "1993-2013") + # Add a title and subtitle
  scale_color_brewer(palette = "Set1") + # Set color palette
  theme_minimal(base_rect_size = 0.25) # Use nicer theme
```


```{r}
pelts %>% # Use the pelts dataset for plotting
  ggplot(aes(x = Year, y = Pelts)) + # Year on x axis, Pelts on y axis
  geom_point(aes(color=Species)) + # Plot a point for each datapoint
  geom_line(aes(color=Species)) + # Plot a line to connect datapoints
  labs(title = "Pelts sold in Newfoundland, Canada",
       subtitle = "1993-2013") + # Add a title and subtitle
  scale_color_brewer(palette = "Set2") + # Set color palette
  theme_minimal(base_rect_size = 0.25) # Use nicer theme
```